# version is set in tools\appveyor.psm1 - Invoke-AppVeyorInstall
environment:
  POWERSHELL_TELEMETRY_OPTOUT: 1
  # Avoid expensive initialization of dotnet cli, see: http://donovanbrown.com/post/Stop-wasting-time-during-NET-Core-builds
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: UnelevatedPesterTests
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    Purpose: ElevatedPesterTests_xUnit_Packaging

# cache version - netcoreapp.2.1-sdk.2.1.401
cache:
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps: Invoke-AppveyorBuild

test_script:
  - ps: Invoke-AppveyorTest -Purpose $env:Purpose

after_test:
  - ps: Invoke-AppVeyorAfterTest

# Packaging
on_finish:
  - ps: if ($env:Purpose -eq 'ElevatedPesterTests_xUnit_Packaging'){ Invoke-AppveyorFinish }
